import '../../public/assets/vendor/libs/jquery/jquery.js'
import '../../public/assets/vendor/libs/popper/popper.js'
import '../../public/assets/vendor/js/bootstrap.js'
import '../../public/assets/vendor/libs/node-waves/node-waves.js'
import '../../public/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js'
import '../../public/assets/vendor/libs/hammer/hammer.js'
import '../../public/assets/vendor/libs/i18n/i18n.js'
import '../../public/assets/vendor/libs/typeahead-js/typeahead.js'
import '../../public/assets/vendor/js/menu.js'

